In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import PlantReactivityAnalysis.data.preparation_eurythmy_data as ped

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Data import

In [3]:
measurements_csv_file= r"../../data/raw/measurements_info.csv"
txt_folder= r"../../data/raw/txt_files"

In [4]:
ped.group_eurythmy_text_data_with_measurements(measurements_csv_file, txt_folder)

In [6]:
df.shape

(625, 46)

In [10]:
df.head()

,id_performance,datetime,plant,generation,wav_file,num_eurythmy,A1_start,A1_end,G1_start,G1_end,D1_start,D1_end,A2_start,A2_end,G2_start,G2_end,D2_start,D2_end,A3_start,A3_end,G3_start,G3_end,D3_start,D3_end,A4_start,A4_end,G4_start,G4_end,D4_start,D4_end,O1_start,O1_end,O2_start,O2_end,O3_start,O3_end,O4_start,O4_end,L1_start,L1_end,L2_start,L2_end,L3_start,L3_end,L4_start,L4_end
id_measurement,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,2023-04-29,salad,1,#1_#1_230429_SE1_M1_BYB_Recording_2023-04-29_1...,1,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2023-04-29,salad,1,#1_#2_230429_SE1_M1_BYB_Recording_2023-04-29_1...,1,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2023-04-29,salad,1,#1_#3_230429_SE1_M1_BYB_Recording_2023-04-29_1...,1,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2023-04-29,salad,2,#1_#4_230429_SK2_M1_BYB_Recording_2023-04-29_1...,0,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2023-04-29,salad,2,#1_#5_230429_SK2_M2_BYB_Recording_2023-04-29_1...,0,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Final meas

In [25]:
meas_eurythmy_path= r"../../data/interim/measurements_with_eurythmy.csv"
figures_folder= r"../../reports/figures/"

In [26]:
df = pd.read_csv(meas_eurythmy_path, index_col='id_measurement')

In [27]:
df.shape

(625, 48)

In [28]:
df.head()

,id_performance,datetime,plant,generation,wav_file,num_eurythmy,A1_start,A1_end,G1_start,G1_end,D1_start,D1_end,A2_start,A2_end,G2_start,G2_end,D2_start,D2_end,A3_start,A3_end,G3_start,G3_end,D3_start,D3_end,A4_start,A4_end,G4_start,G4_end,D4_start,D4_end,O1_start,O1_end,O2_start,O2_end,O3_start,O3_end,O4_start,O4_end,L1_start,L1_end,L2_start,L2_end,L3_start,L3_end,L4_start,L4_end,eurythmy_start,eurythmy_end
id_measurement,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,2023-04-29,salad,1,#1_#1_230429_SE1_M1_BYB_Recording_2023-04-29_1...,1,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,143.0
2,1,2023-04-29,salad,1,#1_#2_230429_SE1_M1_BYB_Recording_2023-04-29_1...,1,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,143.0
3,1,2023-04-29,salad,1,#1_#3_230429_SE1_M1_BYB_Recording_2023-04-29_1...,1,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,143.0
4,1,2023-04-29,salad,2,#1_#4_230429_SK2_M1_BYB_Recording_2023-04-29_1...,0,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,143.0
5,1,2023-04-29,salad,2,#1_#5_230429_SK2_M2_BYB_Recording_2023-04-29_1...,0,17,26,27,36,37,46,47,56,57,66,67,77,79,88,89,98,99,110,112.0,120.0,121.0,131.0,132.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,143.0

In [29]:
df['plant'].value_counts()

plant
salad     270
tomato    182
basil     173
Name: count, dtype: int64

In [30]:
all_columns = df.columns.tolist()
start_index = all_columns.index('A1_start')
end_index = all_columns.index('L4_end')+1
all_columns = all_columns[start_index:end_index]

# Create letter duration
for letter in all_columns:
    # Extract the letter identifier (assuming it's the first part of the column name)
    letter_id = letter.split('_')[0]

    # Calculate the duration and create a new column
    df[f'{letter_id}_duration'] = df[f'{letter_id}_end'] - df[f'{letter_id}_start']

# Extract unique letter identifiers
unique_letters = set(letter.split('_')[0] for letter in all_columns)

# Convert the set back to a list, if needed
unique_letters = sorted(list(unique_letters))

# Create a dictionary to store data grouped by the first letter
data_by_letter = {}

# Populate the dictionary with data
for letter in unique_letters:
    # Construct the duration column name
    duration_col = f'{letter}_duration'

    # Determine the data range and set integer bins accordingly
    data = df[duration_col].dropna().astype(int)
    
    # Get the first letter
    first_letter = letter[0]

    # Add the data to the corresponding letter's group in the dictionary
    if first_letter not in data_by_letter:
        data_by_letter[first_letter] = []
    data_by_letter[first_letter].extend(data)

# Get a new list of the column names that represent the letters
all_columns = df.columns.tolist()
start_index = all_columns.index('A1_duration')
end_index = all_columns.index('L4_duration')+1
durations_starts_ends = all_columns[start_index:end_index]

df['count_letters'] = df[durations_starts_ends].apply(lambda row: (row > 1).sum(), axis=1)

In [37]:
# Assuming df is your DataFrame
new_df = df[(df['count_letters'] != 12) & (df['count_letters'] != 16)]
new_df.shape

(18, 69)

In [38]:
new_df.head(20)

,id_performance,datetime,plant,generation,wav_file,num_eurythmy,A1_start,A1_end,G1_start,G1_end,D1_start,D1_end,A2_start,A2_end,G2_start,G2_end,D2_start,D2_end,A3_start,A3_end,G3_start,G3_end,D3_start,D3_end,A4_start,A4_end,G4_start,G4_end,D4_start,D4_end,O1_start,O1_end,O2_start,O2_end,O3_start,O3_end,O4_start,O4_end,L1_start,L1_end,L2_start,L2_end,L3_start,L3_end,L4_start,L4_end,eurythmy_start,eurythmy_end,A1_duration,G1_duration,D1_duration,A2_duration,G2_duration,D2_duration,A3_duration,G3_duration,D3_duration,A4_duration,G4_duration,D4_duration,O1_duration,O2_duration,O3_duration,O4_duration,L1_duration,L2_duration,L3_duration,L4_duration,count_letters
id_measurement,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7,2,2023-04-29,salad,1,#2_#7_230429_SJ1_M1_BYB_Recording_2023-04-29_1...,1,10,20,21,30,32,43,46,55,56,65,66,75,80,89,90,98,99,109,112.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,121.0,10,9,11,9,9,9,9,8,10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
8,2,2023-04-29,salad,1,#2_#8_230429_SJ1_M1_BYB_Recording_2023-04-29_1...,1,10,20,21,30,32,43,46,55,56,65,66,75,80,89,90,98,99,109,112.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,121.0,10,9,11,9,9,9,9,8,10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
9,2,2023-04-29,salad,1,#2_#9_230429_SJ1_M1_BYB_Recording_2023-04-29_1...,1,10,20,21,30,32,43,46,55,56,65,66,75,80,89,90,98,99,109,112.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,121.0,10,9,11,9,9,9,9,8,10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
10,2,2023-04-29,salad,1,#2_#10_230429_SK1_M1_BYB_Recording_2023-04-29_...,0,10,20,21,30,32,43,46,55,56,65,66,75,80,89,90,98,99,109,112.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,121.0,10,9,11,9,9,9,9,8,10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
11,2,2023-04-29,salad,1,#2_#11_230429_SK1_M2_BYB_Recording_2023-04-29_...,0,10,20,21,30,32,43,46,55,56,65,66,75,80,89,90,98,99,109,112.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,121.0,10,9,11,9,9,9,9,8,10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
12,2,2023-04-29,salad,1,#2_#12_230429_SK1_M3_BYB_Recording_2023-04-29_...,0,10,20,21,30,32,43,46,55,56,65,66,75,80,89,90,98,99,109,112.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,121.0,10,9,11,9,9,9,9,8,10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
91,16,2023-06-01,tomato,1,#16_#91_230601_TJ1_M_BYB_Recording_2023-06-01_...,3,27,40,43,52,56,67,71,81,83,92,95,105,108,120,123,135,137,150,NaN,NaN,NaN,NaN,NaN,NaN,161.0,172.0,176.0,187.0,191.0,202.0,206.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,219.0,13,9,11,10,9,10,12,12,13,NaN,NaN,NaN,11.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN,13
92,16,2023-06-01,tomato,1,#16_#92_230601_TJ1_M_BYB_Recording_2023-06-01_...,3,27,40,43,52,56,67,71,81,83,92,95,105,108,120,123,135,137,150,NaN,NaN,NaN,NaN,NaN,NaN,161.0,172.0,176.0,187.0,191.0,202.0,206.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,219.0,13,9,11,10,9,10,12,12,13,NaN,NaN,NaN,11.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN,13
93,16,2023-06-01,tomato,1,#16_#93_230601_TJ1_M_BYB_Recording_2023-06-01_...,3,27,40,43,52,56,67,71,81,83,92,95,105,108,120,123,135,137,150,NaN,NaN,NaN,NaN,NaN,NaN,161.0,172.0,176.0,187.0,191.0,202.0,206.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,219.0,13,9,11,10,9,10,12,12,13,NaN,NaN,NaN,11.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN,13
94,16,2023-06-01,tomato,1,#16_#94_230601_TK1_M_BYB_Recording_2023-06-01_...,0,27,40,43,52,56,67,71,81,83,92,95,105,108,120,123,135,137,150,NaN,NaN,NaN,NaN,NaN,NaN,161.0,172.0,176.0,187.0,191.0,202.0,206.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,219.0,13,9,11,10,9,10,12,12,13,NaN,NaN,NaN,11.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN,13
95,16,2023-06-01,tomato,1,#16_#95_230601_TK1_M_BYB_Recording_2023-06-01_...,0,27,40,43,52,56,67,71,81,83,92,95,105,108,120,123,135,137,150,NaN,NaN,NaN,NaN,NaN,NaN,161.0,172.0,176.0,187.0,191.0,202.0,206.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,219.0,13,9,11,10,9,10,12,12,13,NaN,NaN,NaN,11.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN,13
96,16,2023-06-01,tomato,1,#16_#96_230601_TK1_M_BYB_Recording_2023-06-01_...,0,27,40,43,52,56,67,71,81,83,92,95,105,108,120,123,135,137,150,NaN,NaN,NaN,NaN,NaN,NaN,161.0,172.0,176.0,187.0,191.0,202.0,206.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,219.0,13,9,11,10,9,10,12,12,13,NaN,NaN,NaN,11.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN,13
614,106,2023-09-30,salad,4,#106_#614_230930_SE4_M_BYB_Recording_2023-09-3...,1,12,24,26,35,36,46,49,59,61,70,72,81,84,95,97,106,107,117,119.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,129.0,12,9,10,10,9,9,11,9,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
615,106,2023-09-30,salad,4,#106_#615_230930_SE4_M_BYB_Recording_2023-09-3...,1,12,24,26,35,36,46,49,59,61,70,72,81,84,95,97,106,107,117,119.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,129.0,12,9,10,10,9,9,11,9,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
616,106,2023-09-30,salad,4,#106_#616_230930_SE4_M_BYB_Recording_2023-09-3...,1,12,24,26,35,36,46,49,59,61,70,72,81,84,95,97,106,107,117,119.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,129.0,12,9,10,10,9,9,11,9,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
617,106,2023-09-30,salad,4,#106_#617_230930_SK4_M_BYB_Recording_2023-09-3...,0,12,24,26,35,36,46,49,59,61,70,72,81,84,95,97,106,107,117,119.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,129.0,12,9,10,10,9,9,11,9,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
618,106,2023-09-30,salad,4,#106_#618_230930_SK4_M_BYB_Recording_2023-09-3...,0,12,24,26,35,36,46,49,59,61,70,72,81,84,95,97,106,107,117,119.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,129.0,12,9,10,10,9,9,11,9,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
619,106,2023-09-30,salad,4,#106_#619_230930_SK4_M_BYB_Recording_2023-09-3...,0,12,24,26,35,36,46,49,59,61,70,72,81,84,95,97,106,107,117,119.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,129.0,12,9,10,10,9,9,11,9,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10

## Data Comprehension

In [26]:
# Get a new list of the column names that represent the letters
all_columns = df.columns.tolist()
start_index = all_columns.index('A1_duration')
end_index = all_columns.index('L4_duration')-1
durations_starts_ends = all_columns[start_index:end_index]

In [27]:
df['count_letters'] = df[durations_starts_ends].apply(lambda row: (row > 1).sum(), axis=1)

In [ ]:
sum_count_letters_by_plant = df.groupby('plant')['count_letters'].sum()

print(sum_count_letters_by_plant)

### Eurythmy Letter Gestures

Calculate duration of eurythmy gestures

In [19]:
all_columns = df.columns.tolist()
start_index = all_columns.index('A1_start')
end_index = all_columns.index('L4_end')+1
all_columns = all_columns[start_index:end_index]

['A1_start', 'A1_end', 'G1_start', 'G1_end', 'D1_start', 'D1_end', 'A2_start', 'A2_end', 'G2_start', 'G2_end', 'D2_start', 'D2_end', 'A3_start', 'A3_end', 'G3_start', 'G3_end', 'D3_start', 'D3_end', 'A4_start', 'A4_end', 'G4_start', 'G4_end', 'D4_start', 'D4_end', 'O1_start', 'O1_end', 'O2_start', 'O2_end', 'O3_start', 'O3_end', 'O4_start', 'O4_end', 'L1_start', 'L1_end', 'L2_start', 'L2_end', 'L3_start', 'L3_end', 'L4_start', 'L4_end']

In [20]:
# Create letter duration
for letter in all_columns:
    # Extract the letter identifier (assuming it's the first part of the column name)
    letter_id = letter.split('_')[0]

    # Calculate the duration and create a new column
    df[f'{letter_id}_duration'] = df[f'{letter_id}_end'] - df[f'{letter_id}_start']

# Extract unique letter identifiers
unique_letters = set(letter.split('_')[0] for letter in all_columns)

# Convert the set back to a list, if needed
unique_letters = sorted(list(unique_letters))

Group all similar letters

In [21]:
# Create a dictionary to store data grouped by the first letter
data_by_letter = {}

# Populate the dictionary with data
for letter in unique_letters:
    # Construct the duration column name
    duration_col = f'{letter}_duration'

    # Determine the data range and set integer bins accordingly
    data = df[duration_col].dropna().astype(int)
    
    # Get the first letter
    first_letter = letter[0]

    # Add the data to the corresponding letter's group in the dictionary
    if first_letter not in data_by_letter:
        data_by_letter[first_letter] = []
    data_by_letter[first_letter].extend(data)

Plot histograms of the letters

In [ ]:
# Create histograms for each group of letters
for first_letter, data in data_by_letter.items():
    # Determine the data range and set integer bins accordingly
    data_range = int(max(data)) - int(min(data))
    bins = np.arange(int(min(data)), int(max(data)) + 2, 1)

    # Calculate the mean of the data
    mean_value = np.mean(data)

    # Plot the histogram for the current group of letters with integer bins
    plt.figure(figsize=(8, 4))  # Optional: Adjust figure size
    n, bins, patches = plt.hist(data, bins=bins, edgecolor='black', align='left', rwidth=0.8)  # Use align='left' and adjust rwidth
    plt.title(f'Letter {first_letter} Duration')
    plt.xlabel('Seconds')
    plt.ylabel('Frequency')
    
    # Set x-axis ticks to display only integers
    plt.xticks(np.arange(int(min(data)), int(max(data)) + 1, 1))

    # Add a red vertical line for the mean
    plt.axvline(mean_value, color='lightcoral', linestyle='solid', linewidth=2, label='Mean')
    plt.legend()  # Show the legend with the mean line
    file_path= os.path.join(figures_folder, f'letter_{first_letter}_duration_histogram')
    plt.savefig(file_path)
    plt.show()

In [ ]:
# Create a dictionary to store data grouped by the first letter
data_by_letter = {}

# Populate the dictionary with data
for letter in unique_letters:
    # Construct the duration column name
    duration_col = f'{letter}_duration'

    # Determine the data range and set integer bins accordingly
    data = df[duration_col].dropna().astype(int)
    
    # Get the first letter
    first_letter = letter[0]

    # Add the data to the corresponding letter's group in the dictionary
    if first_letter not in data_by_letter:
        data_by_letter[first_letter] = []
    data_by_letter[first_letter].extend(data)

# Create a histogram for all letters combined
all_data = [data for data_list in data_by_letter.values() for data in data_list]
data_range = int(max(all_data)) - int(min(all_data))
bins = np.arange(int(min(all_data)), int(max(all_data)) + 2, 1)

# Calculate the mean of the data
mean_value = np.mean(all_data)

plt.figure(figsize=(8, 4))  # Optional: Adjust figure size
n, bins, patches = plt.hist(all_data, bins=bins, edgecolor='black', align='left', rwidth=0.8)
plt.title('Combined Histogram of All Letters')
plt.xlabel('Duration')
plt.ylabel('Frequency')
plt.axvline(mean_value, color='lightcoral', linestyle='solid', linewidth=2, label='Mean')
plt.legend()  # Show the legend with the mean line
plt.xticks(np.arange(int(min(all_data)), int(max(all_data)) + 1, 1))

# Annotate each bar with its frequency
for count, rect in zip(n, patches):
    height = rect.get_height()
    plt.annotate(f'{int(count)}', xy=(rect.get_x() + rect.get_width() / 2, height),
                 xytext=(0, 3), textcoords='offset points', ha='center', va='bottom')
file_path= os.path.join(figures_folder, 'letter_duration_histogram')
plt.savefig(file_path)
plt.show()

### Eurythmy Performances

In [ ]:
# Define your colors dictionary
colors = {'salad': 'lightgreen', 'tomato': 'lightcoral', 'basil': 'green'}

# Calculate 'eurythmy_duration' as before
df['eurythmy_duration'] = df['eurythmy_end'] - df['eurythmy_start']

# Prepare data for stacked histogram
plant_types = df['plant'].unique()
hist_data = [df[df['plant'] == plant]['eurythmy_duration'].dropna().astype(int) for plant in plant_types]
colors = [colors.get(plant, 'gray') for plant in plant_types]

# Create a stacked histogram
plt.figure(figsize=(8, 6))
plt.hist(hist_data, bins=20, edgecolor='black', color=colors, label=plant_types, stacked=True)

plt.title('Performance Duration by Plant')
plt.xlabel('Duration')
plt.ylabel('Frequency')

# Adjust x-axis ticks to display fewer values and increase font size for readability
min_duration = int(df['eurythmy_duration'].min())
max_duration = int(df['eurythmy_duration'].max())
plt.xticks(np.arange(min_duration, max_duration + 1, (max_duration - min_duration) // 4), fontsize=12) # Adjust the step for ticks

plt.legend()  # Show the legend for different plants

# Calculate and plot the average line
average_eurythmy_duration = np.mean(df['eurythmy_duration'])
plt.axvline(average_eurythmy_duration, color='red', linestyle='dashed', linewidth=2, label='Mean')
plt.legend()  # Update the legend to include the mean line

file_path= os.path.join(figures_folder, 'performance_duration_by_plant')
plt.savefig(file_path)
plt.show()

In [ ]:
for plant in plant_types:
    durations = df[df['plant'] == plant]['eurythmy_duration'].dropna().astype(int)
    print(f"Statistics for {plant}:")
    print(f"  Mean Duration: {durations.mean():.2f}")
    print(f"  Median Duration: {durations.median():.2f}")
    print(f"  Min Duration: {durations.min()}")
    print(f"  Max Duration: {durations.max()}")
    print()

Check the labelling went well

In [ ]:
# Check from the column 'A1_start' to the end for each row if any value is lower than the one before
results = []
for index, row in df.iterrows():
    # Get the values from 'A1_start' to the end of the row
    values = row.loc['A1_start':]

    # Check if any value is lower than the previous one
    is_decreasing = any(values.iloc[i] < values.iloc[i-1] for i in range(1, len(values)))
    results.append(is_decreasing)
    
df['is_decreasing'] = results

# Add the results to the DataFrame
print(df['is_decreasing'].value_counts())

print("Every eurythmy letter starts when the one before has ended")